/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApplyMessage: typeof import('./src/components/ApplyMessage/index.vue')['default']
    BottomInput: typeof import('./src/components/BottomInput/index.vue')['default']
    Button: typeof import('./src/components/Button/index.vue')['default']
    ChatPopup: typeof import('./src/components/ChatPopup/index.vue')['default']
    ContactHome: typeof import('./src/components/ContactHome/index.vue')['default']
    DefaultContent: typeof import('./src/components/DefaultContent/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Emoji: typeof import('./src/components/Emoji/index.vue')['default']
    FriendOrGroupList: typeof import('./src/components/FriendOrGroupList/index.vue')['default']
    HeaderMenu: typeof import('./src/components/HeaderMenu/index.vue')['default']
    Input: typeof import('./src/components/Input/index.vue')['default']
    MarkDownEdit: typeof import('./src/components/MarkDownEdit/index.vue')['default']
    MessageDetail: typeof import('./src/components/MessageDetail/index.vue')['default']
    MessageList: typeof import('./src/components/MessageList/index.vue')['default']
    RightKeyMenu: typeof import('./src/components/RightKeyMenu/index.vue')['default']
    RightKeyMenuDetail: typeof import('./src/components/RightKeyMenuDetail/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search/index.vue')['default']
    SetupBtn: typeof import('./src/components/SetupBtn/index.vue')['default']
    SpaceList: typeof import('./src/components/SpaceList/index.vue')['default']
    TelephoneWin: typeof import('./src/components/TelephoneWin/index.vue')['default']
    Toast: typeof import('./src/components/Toast/index.vue')['default']
    WindowsBtn: typeof import('./src/components/WindowsBtn/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
